### ISSUE TITLE
NTR: Research > Survey

### ISSUE THREAD

**Issue by andscoaafc** [cidgoh/GRDI_AMR_One_Health#5]
# AMR-GRDI Specification - New Term Request (NTR)
_May request multiple terms in a single issue - delete the fields irrelevant to your request._

## Picklist Item(s)

Associated Field(s): purpose_of_sampling

Label: Research > Survey
Definition/Description: Survey study conducted for research purposes outside of a mandated requirement. 
Definition Source:
Synonyms or alternative labels:
Additional Comments (not an annotation):

--- 
Contributor Attribution: Andrew Scott (AAFC)

**Comment by griffie** [comment]
Hi Andrew - thanks for trying out the new term request system! 
For this term, when you say "survey study", do you mean the same kind of thing as the Surveillance terms we already have (baseline or targeted) but it's for for research rather than for operational purposes (like as opposed to public health surveillance or monitoring of sentinel sites)?

**Comment by andscoaafc** [comment]
Yes, for research instead of the types of surveys that PHAC and CFIA do... an example of the type we do... 
Distribution and diversity of Escherichia coli populations in the South Nation River drainage basin, eastern Ontario, Canada.
Lyautey E, Lu Z, Lapen DR, Wilkes G, Scott A, Berkers T, Edge TA, Topp E. Appl Environ Microbiol. 2010 Mar;76(5):1486-96. doi: 10.1128/AEM.02288-09. Epub 2009 Dec 28. PMID: 20038693

**Comment by griffie** [comment]
We've added "Survey study" under Research in the "purpose of sampling" field.

How does that sound?
