### ISSUE TITLE
NTR: Building > Digester

### ISSUE THREAD

**Issue by andscoaafc** [cidgoh/GRDI_AMR_One_Health#6]
# AMR-GRDI Specification - New Term Request (NTR)
_May request multiple terms in a single issue - delete the fields irrelevant to your request._

## Picklist Item(s)

Associated Field(s): environmental_site

Label: Digester
Definition/Description: Aerobic/Anaerobic Digester for on-Farm digestion of manure
Definition Source:
Synonyms or alternative labels:
Additional Comments (not an annotation):

--- 
Contributor Attribution: Andrew Scott (AAFC)

**Comment by griffie** [comment]
Is a digester a building with equipment in it, or is the digester the equipment itself (big tank where microbes digest manure)?

**Comment by andscoaafc** [comment]
It can be both...

**Comment by griffie** [comment]
This will all sound pedantic but your answers help us place the terms in the hierarchy (which is why I keep bugging you). :)

Could we differentiate a Digester (building) from Digester (equipment)? Where the equipment could be the tank and pipes etc and the building in the housing/building enclosing the equipment?

The Digester (building) would be under environmental site and the Digester (equipment) would be under environmental material (because the first is a place and the the latter is a thing). How does that sound?

**Comment by griffie** [comment]
After some discussion, we've added "Manure digester facility" to environmental site, and "Manure digester equipment" to environmental material. 

How does that sound?
